NAMESPACE Simatic.Ax.LPMLV2022
    TYPE
        /// Unit modes according to ANSI/ISA-TR88.00.02-2022 (PackML).
        Mode : DINT (
            /// OMAC PackMLV2022 unit mode Invalid
            INVALID := DINT#0,
            /// OMAC PackMLV2022 unit mode Production
            PRODUCTION := DINT#1,
            /// OMAC PackMLV2022 unit mode Maintenance
            MAINTENANCE := DINT#2,
            /// OMAC PackMLV2022 unit mode Manual
            MANUAL := DINT#3,
            /// OMAC PackMLV2022 user-defined unit mode 01
            USER_01 := DINT#4,
            /// OMAC PackMLV2022 user-defined unit mode 02
            USER_02 := DINT#5,
            /// OMAC PackMLV2022 user-defined unit mode 03
            USER_03 := DINT#6,
            /// OMAC PackMLV2022 user-defined unit mode 04
            USER_04 := DINT#7,
            /// OMAC PackMLV2022 user-defined unit mode 05
            USER_05 := DINT#8,
            /// OMAC PackMLV2022 user-defined unit mode 06
            USER_06 := DINT#9,
            /// OMAC PackMLV2022 user-defined unit mode 07
            USER_07 := DINT#10,
            /// OMAC PackMLV2022 user-defined unit mode 08
            USER_08 := DINT#11,
            /// OMAC PackMLV2022 user-defined unit mode 09
            USER_09 := DINT#12,
            /// OMAC PackMLV2022 user-defined unit mode 10
            USER_10 := DINT#13,
            /// OMAC PackMLV2022 user-defined unit mode 11
            USER_11 := DINT#14,
            /// OMAC PackMLV2022 user-defined unit mode 12
            USER_12 := DINT#15,
            /// OMAC PackMLV2022 user-defined unit mode 13
            USER_13 := DINT#16,
            /// OMAC PackMLV2022 user-defined unit mode 14
            USER_14 := DINT#17,
            /// OMAC PackMLV2022 user-defined unit mode 15
            USER_15 := DINT#18,
            /// OMAC PackMLV2022 user-defined unit mode 16
            USER_16 := DINT#19,
            /// OMAC PackMLV2022 user-defined unit mode 17
            USER_17 := DINT#20,
            /// OMAC PackMLV2022 user-defined unit mode 18
            USER_18 := DINT#21,
            /// OMAC PackMLV2022 user-defined unit mode 19
            USER_19 := DINT#22,
            /// OMAC PackMLV2022 user-defined unit mode 20
            USER_20 := DINT#23,
            /// OMAC PackMLV2022 user-defined unit mode 21
            USER_21 := DINT#24,
            /// OMAC PackMLV2022 user-defined unit mode 22
            USER_22 := DINT#25,
            /// OMAC PackMLV2022 user-defined unit mode 23
            USER_23 := DINT#26,
            /// OMAC PackMLV2022 user-defined unit mode 24
            USER_24 := DINT#27,
            /// OMAC PackMLV2022 user-defined unit mode 25
            USER_25 := DINT#28,
            /// OMAC PackMLV2022 user-defined unit mode 26
            USER_26 := DINT#29,
            /// OMAC PackMLV2022 user-defined unit mode 27
            USER_27 := DINT#30,
            /// OMAC PackMLV2022 user-defined unit mode 28
            USER_28 := DINT#31
            );
    END_TYPE
END_NAMESPACE
